### PR TITLE
Bugfix #147 and Bugfix font selection

### PR DESCRIPTION
**Pull request by ukscid**
I start to use github with two small fixes.
I am not familar with github, so i hope it is fine.

It's perfect, thanks.
The code needs to be improved, I will comment the commits.

### CODE REVIEW

**Review by benini — CHANGES_REQUESTED** [review]
I'm not sure what's the point of {Bold\ Italic}.
However -values takes a list, so it should be "-values [list $style]"
Please check if that fix the problem

**Review by benini — CHANGES_REQUESTED** [review]
There are a few thing that need to be fixed here:
1) e.first should e a std::string: if that is the case it should not use strcmp but just ==
2) the comparision should not be case sensitive: if a game contains a "Setup" tag we don't want to add another "SetUp"
3) Position with a non-standard start position are uncommon, but now we compare every single tag for every single game to "SetUp", even if it is non necessary.
4) If I remember correctly, Game::WritePGN is used for many things. Not only html or latex exports, but also for the PGN window. I don't want it to show a non-existent "SetUp" tag if the game is stored in a SCID4 database.

**Comment by ukscid** [comment]
> I'm not sure what's the point of {Bold\ Italic}.
> However -values takes a list, so it should be "-values [list $style]"
> Please check if that fix the problem

Yes. -values [list $style] work also, like {Bold\ Italic}. Both represent one single item.
I changed the patch.

**Comment by ukscid** [comment]
> I'm not sure what's the point of {Bold\ Italic}.
> However -values takes a list, so it should be "-values [list $style]"
> Please check if that fix the problem

Changed to "-values [list $style]". This works, like  {Bold\ Italic}

**Comment by ukscid** [comment]
> There are a few thing that need to be fixed here:
> 
> 1. e.first should e a std::string: if that is the case it should not use strcmp but just ==
> 2. the comparision should not be case sensitive: if a game contains a "Setup" tag we don't want to add another "SetUp"
> 3. Position with a non-standard start position are uncommon, but now we compare every single tag for every single game to "SetUp", even if it is non necessary.
> 4. If I remember correctly, Game::WritePGN is used for many things. Not only html or latex exports, but also for the PGN window. I don't want it to show a non-existent "SetUp" tag if the game is stored in a SCID4 database.

Changed the 4 topic you mentioned

**Comment by benini** [comment]
It seems to me that only the point nr. 2 has been fixed.
1) If you know the length of a string in advance, it is more efficient to compare before if they are equal in length. It is done automatically in the STL if you use == instead of strcmp: that was the point of my comment. It is also done in the google's abseil library before doing an icase compare: https://github.com/abseil/abseil-cpp/blob/master/absl/strings/match.cc#L22
3) Nothing has changed, the patch keep looking for the "SetUp" tag even for games starting from the standard position 
4) A simple grep is enough to view that PGN_FORMAT_Plain is used in many places, not only when exporting games to a PGN file.

When changing some code it is necessary to check all the side effects that are generated, many IDE have the ability to report where a function is called (for example Visual Studio have a "View Call Hierarchy").
Game::WritePGN is a complex, messy, used for many things, function and it is not the right place where this change should be placed.

**Pull request closed without merging**
