### PR TITLE
arrange fics clocks

### PR DESCRIPTION
**Pull request by ukscid**
arrange fics clocks according board orientation: flips clock when board is flipped

### CODE REVIEW

**Comment by benini** [comment]
It is obviously not ok to append "::fics::arrangeClocks" to every board::flip line:
1) There are other places where it is invoked (the 1st that I can think of is when . is pressed )
2) It is a huge maintenance problem: how someone is supposed to be aware that in some cases when invoking board::flip it should also invoke a fics function?
3) It assumes that exists only one board: it would be very useful to watch multiple games and this makes that goal even harder.

**Comment by ukscid** [comment]
Yes, the conditions for this functionality are not good.
3 alternatives:
a) trace add variable ::board::_flip(.main.board) ::fics::arrangeClocks
and
trace remove ...
when fics window is closed
(trace is a bad function?)

b) additional button in the fics-window to flip the clocks

c) only arrange on start of the fics-window, no change when board flips

other ideas?

**Comment by benini** [comment]
Let's be satisfied, at least for the moment, with c)
(The "correct" solution if one would be writing this from scratch would be to not draw the clocks in the fics window but let the board draw and handle them. The FICS code would just invoke a function ::board::setClocks $w $whiteTime $blackTime without having to worry if it is flipped or not).

**Comment by benini** [comment]
merged

**Pull request closed without merging**
